# Build (compilar la app)
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copiar el archivo .csproj desde la subcarpeta del proyecto
COPY "Nazar Prueba/*.csproj" ./
RUN dotnet restore

# Copiar el resto del código fuente
COPY "Nazar Prueba/" ./
RUN dotnet publish -c Release -o out

# Runtime (ejecutar la app)
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out .
EXPOSE 5000
EXPOSE 5001
ENTRYPOINT ["dotnet", "Nazar.Api.dll"]
